Question 5) How many records contain a decimal number?

In [10]:
import pandas as pd
import re
# Load the uploaded CSV file
file_path = 'Downloads/Data.csv'
df = pd.read_csv(file_path)

# Display the first few rows and the column names to understand the structure
df.head(), df.columns

(                                                Data
 0  Watch or listen live weekdays at 8:30am MT at ...
 1  Watch or listen live weekdays at 8:30am MT at ...
 2               Chubby And Hot, Always Stir The Pot!
 3               Chubby And Hot, Always Stir The Pot!
 4  Journalist, publisher of Rebel News — telling ...,
 Index(['Data'], dtype='object'))

In [11]:
# Regex to find decimal numbers
decimal_pattern = r'\b\d+\.\d+\b'

# Count records containing decimal numbers
decimal_count = df['Data'].str.contains(decimal_pattern, regex=True).sum()

print("Number of records with a decimal number:", decimal_count)

Number of records with a decimal number: 25

In [12]:
# Filter rows with decimal numbers
decimal_rows = df[df['Data'].str.contains(r'\b\d+\.\d+\b', regex=True)]

# Display them
decimal_rows

                                                   Data
3208  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
3663  hier schreiben die Hühner aus dem Stall  (*25....
3682  Providing RV repair, parts & accessories, 24/7...
3691  Providing RV repair, parts & accessories, 24/7...
3861  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
4316  hier schreiben die Hühner aus dem Stall  (*25....
4335  Providing RV repair, parts & accessories, 24/7...
4344  Providing RV repair, parts & accessories, 24/7...
4476  Providing RV repair, parts & accessories, 24/7...
4568  #openaccess journal published by@MDPIOpenAcces...
4626  Hoping hardcore twitter 2.0 lets me express ho...
4943  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
5113  Playing Southern Saskatchewan's Best Country! ...
5231  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
5244  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...
5263  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...
5445  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
5887  #openaccess journal published by@MDPIOpenAcces...
5945  Hoping hardcore twitter 2.0 lets me express ho...
6262  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
6432  Playing Southern Saskatchewan's Best Country! ...
6550  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...
6563  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...
6582  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...
6764  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...

In [13]:
# Extract and display records with decimal matches
df['decimal_matches'] = df['Data'].apply(lambda x: re.findall(r'\b\d+\.\d+\b', str(x)))
decimal_rows = df[df['decimal_matches'].map(len) > 0]

decimal_rows[['Data', 'decimal_matches']]

                                                   Data    decimal_matches
3208  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
3663  hier schreiben die Hühner aus dem Stall  (*25....             [26.4]
3682  Providing RV repair, parts & accessories, 24/7...  [1.587, 989.1271]
3691  Providing RV repair, parts & accessories, 24/7...  [1.587, 989.1271]
3861  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
4316  hier schreiben die Hühner aus dem Stall  (*25....             [26.4]
4335  Providing RV repair, parts & accessories, 24/7...  [1.587, 989.1271]
4344  Providing RV repair, parts & accessories, 24/7...  [1.587, 989.1271]
4476  Providing RV repair, parts & accessories, 24/7...  [1.587, 989.1271]
4568  #openaccess journal published by@MDPIOpenAcces...       [3.905, 3.2]
4626  Hoping hardcore twitter 2.0 lets me express ho...              [2.0]
4943  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
5113  Playing Southern Saskatchewan's Best Country! ...            [100.7]
5231  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
5244  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...       [96.5, 96.5]
5263  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...       [96.5, 96.5]
5445  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
5887  #openaccess journal published by@MDPIOpenAcces...       [3.905, 3.2]
5945  Hoping hardcore twitter 2.0 lets me express ho...              [2.0]
6262  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
6432  Playing Southern Saskatchewan's Best Country! ...            [100.7]
6550  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]
6563  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...       [96.5, 96.5]
6582  96.5 CKFM - All Hit Country!\n📻 96.5 FM \n🌐 ck...       [96.5, 96.5]
6764  AIR 106.1 FM + DiscoverAirdrie Local News.\nWa...            [106.1]

**Therefore, 25 records contain decimals**